conky.config = {
    alignment = 'top_right',
    gap_x = 10,
    gap_y = 10,

    own_window = true,
    own_window_type = 'normal',
    own_window_hints = 'undecorated,skip_taskbar,skip_pager,sticky',
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_transparent = true,



    double_buffer = true,
    update_interval = 1,

    use_xft = true,
    font = 'DejaVu Sans Mono:size=11',
    xftalpha = 1,
    override_utf8_locale = true,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,
    default_color = 'white',

    minimum_width = 310,
    maximum_width = 310,
};

conky.text = [[
${alignc}${color 00aaff}${font DejaVu Sans Mono:size=49}${time %H:%M:%S}${font}${color}
${alignc}${color 00aaff}${font Dejavu Sans Nono:size=15.5}${time %A %d %B %Y}${font}${color}
${alignc}${kernel}
${alignc}Uptime: ${uptime}
Motherboard Temp:          ${color ff1493}${execi 86400 sensors | grep 'temp1' | awk '{print $2}'}${color}  
RAM: ${color 00ffff}${mem}${color} / ${memmax} (${color 00ffff}${memperc}${color}%)${color 00ffff}${membar 8,62}${color}
Swap: ${alignr}${swap} / ${swapmax}  
Disk /: ${fs_used /} / ${fs_size /} (${fs_free_perc /}% free)
CPU Temp: ${alignr}${color ff0000}${font Dejavu Sans Mono:bold:size=17}${execi 2 sensors | grep 'Package id 0' | awk '{print $4}'}${font}${color}  
Freq: ${alignr}${color ff0000}${freq}${color}
Ping: ${alignr}${color daa520}${execi 600 ping -c1 google.com | awk -F'=' '/time=/{print $4 " "}'}${color}
CPU:         ${color ff0000}${font Dejavu Sans Mono:bold:size=14}${cpu cpu0}${font}${color}%   RAM:         ${color 00ffff}${memperc}${color}%  
${cpugraph 40,155 55aaff  ff0000}${alignr}${memgraph 40,155 00ff00 00ffff}
${color ff0000}${cpubar 8,150}${color}${alignr}${color 00ffff}${membar 8,150}${color}
ReadA: ${diskio_read sda}${alignr}WriteA: ${diskio_write sda}
${diskiograph_read sda 40,155 00ff00 ffd700}${alignr}${diskiograph_write sda 40,155 ff0000 d2691e}
ReadB: ${diskio_read sdb}${alignr}WriteB: ${diskio_write sdb}     
${diskiograph_read sdb 40,155 00ff00 ffd700}${alignr}${diskiograph_write sdb 40,155 ff0000 d2691e}
ReadC: ${diskio_read sdc}${alignr}WriteC: ${diskio_write sdc}
${diskiograph_read sdc 40,155 00ff00 ffd700}${alignr}${diskiograph_write sdc 40,155 ff0000 d2691e}
Upload: ${upspeed enp4s0}${alignr}Download: ${downspeed enp4s0}
${upspeedgraph enp4s0 40,155 55aaff 4b0082}${alignr}${downspeedgraph enp4s0 40,155 55aaff 00ff00}




]];
